[workspace]
authors = ["ptim <tpinkhassik@gmail.com>"]
channels = ["pytorch", "pyg", "conda-forge"]
name = "gnn"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pyg = ">=2.6.1,<3"
pytorch = ">=2.4.1,<3"
torchvision = ">=0.19.1,<0.20"
rdkit = ">=2025.9.1,<2026"
numpy = ">=2.3.4,<3"
matplotlib = ">=3.10.7,<4"
pandas = ">=2.3.3,<3"
tqdm = ">=4.67.1,<5"
networkx = ">=3.5,<4"
ipykernel = ">=7.0.1,<8"
ipywidgets = ">=8.1.7,<9"
